### ISSUE TITLE
The signature of COBYQA

### ISSUE THREAD

**Issue by zaikunzhang** [cobyqa/cobyqa#110]
It looks quite different from `pdfo.pdfo` and `pdfo.cobyla`. Is it the case? If yes, what is the reason?

https://cobyqa.com/en/latest/ref/generated/cobyqa.minimize.html
https://pdfo.net/python/generated/pdfo.cobyla.html
https://pdfo.net/python/generated/pdfo.pdfo.html

**Comment by ragonneau** [comment]
I intentionally made it simple so that it is easy to interface with any other package (and other languages).

If you think it's necessary, I can make it look like `scipy.optimize.minimize` (by using their classes `scipy.minimize.Bounds`, `scipy.minimize.LinearConstraints`, and `scipy.minimize.NonlinearConstraints`).

Cheers,
Tom.

**Comment by zaikunzhang** [comment]
I trust your choice as long as you 1. think for the users and 2. intend to do what you do. Thanks.

**Comment by ragonneau** [comment]
I think so. The idea I had was to match the Python signature with the mathematical formulation. Basically, users should call COBYQA as

```python
res = minimize(fun, x0, xl=xl, xu=xu, aub=aub, bub=bub, aeq=aeq, beq=beq, cub=cub, ceq=ceq)
```
where
1. `x0`, `xl`, `xu`, `aub`, `bub`, `aeq`, `beq` are arrays (not necessarily NumPy arrays, I do the conversion),
2. `fun`, `cub`, and `ceq` are functions (I also convert the returned type of `cub` and `ceq`), and
3. of course, all the constraint inputs are optional.

Cheer,
Tom.
